import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white shadow-md p-4 flex justify-between items-center">
      <Link href="/" className="text-2xl font-bold text-blue-600">
        Fixoll
      </Link>
      <div className="space-x-6">
        <Link href="/services" className="text-gray-700 hover:text-blue-600">
          Servicios
        </Link>
        <Link href="/profile" className="text-gray-700 hover:text-blue-600">
          Perfil
        </Link>
        <Link href="/about" className="text-gray-700 hover:text-blue-600">
          About Us
        </Link>
        <Link href="/auth/login" className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700">
          Login
        </Link>
      </div>
    </nav>
    <div>
    {children}

    </div>
        
      </body>
    </html>
  );
}
